import Head from "next/head";
import GridHelper from "../src/components/Layout/Grid/GridHelper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GridHelper />
      Hello World
    </>
  );
}
